# Generated by Django 4.1.4 on 2022-12-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
